### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tsuchinoko0102** [Tsuchinoko0102/furima-29278#10]
## FURIMA URL
https://furima-29278.herokuapp.com/

## BASIC認証
ID: YTsuchiya
Pass: tsuchiya444448

## 出品者情報
Mail: ayaka@hoge.jp
Pass: tsuchiya444448

## 購入者情報
Mail: izumi@hoge.jp
Pass: tsuchiya444448

## PAY.JP用テストカード情報
Number: 4242424242424242
EXP: 24年2月
CVC: 123

ご確認のほど何卒よろしくお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
